[tool.pylint.master]
extension-pkg-whitelist = "pydantic"
job = 0
suggestion-mode = "yes"

[tool.pylint.format]
max-line-length = 120

[tool.pylint.message_control]
disable = ["missing-docstring"]

[tool.black]
line-length = 120

[tool.mypy]
ignore_missing_imports = true
plugins = ["pydantic.mypy"]

[tool.isort]
include_trailing_comma = true
line_length = 120
multi_line_output = 3
profile = "black"
src_paths = ["."]
use_parentheses = true


[tool.pytest.ini_options]
addopts = " -svv --cov=."
testpaths = ["tests"]


[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "raise AssertionError",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
]
fail_under = 90.0
omit = ["main.py"]
show_missing = true
skip_covered = true
skip_empty = true
sort = "miss"

[tool.coverage.path]
source = "."